### ISSUE TITLE
Error message after whats app opens

### ISSUE THREAD

**Issue by Moe234** [DollarAkshay/WhatsApp-Chatbot#11]
Hi please help. I'm getting this error as soon as whats app opens on my browser.

DevTools listening on ws://127.0.0.1:12880/devtools/browser/fb811799-1732-4a26-8512-1f6b259432cd
Traceback (most recent call last):
  File "C:/Users/DellXPS/PycharmProjects/WhatsApp-Chatbot-master/Whatsapp_Chat_Bot.py", line 34, in <module>
    driver.execute_script("window.open('','_blank');")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 634, in execute_script
    return self.execute(command, dict(script=script, args=converted_args))['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.24.417431 (9aea000394714d2fbb20850021f6204f2256b9cf),platform=Windows NT 10.0.17134 x86_64)

**Comment by fontanon** [comment]
Same here.

**Comment by huzoorbux** [comment]
same here.

**Comment by ashwinvk94** [comment]
same here
