### ISSUE TITLE
error

### ISSUE THREAD

**Issue by josep112** [DollarAkshay/WhatsApp-Chatbot#2]
I am using Debian 8 desktop, I installed google chrome but I can not do it could you help me?

root@debian:/usr/src/WhatsApp-Chatbot-master# python3 Whatsapp_Chat_Bot.py 
Traceback (most recent call last):
  File "Whatsapp_Chat_Bot.py", line 27, in <module>
    driver = webdriver.Chrome(chrome_options=options, executable_path=driverPath)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.16.0-4-amd64 x86_64)

**Comment by DollarAkshay** [comment]
I guess your dataPath is not accessible.

Try changing Line : 27 from
`driver = webdriver.Chrome(chrome_options=options, executable_path=driverPath)`
TO
`driver = webdriver.Chrome(executable_path=driverPath)`

Make sure you have also downloaded the driver folder.

**Comment by DollarAkshay** [comment]
Closing the Issue
